---
logo0:
  type: tpl-part
  tpl_part: basic-logo-simple
nav-menu-header1:
  debug_label: Nav Menu
  debug_type: menu
  type: tpl-part
  tpl_part: basic-nav-menu-bootstrap
  menu:
    container: div
    container_class: >
      nav-menu collapse navbar-collapse
      navbar-ex1-collapse no-margin
    theme_location: main-menu-login
    menu_class: nav navbar-nav
    fallback_cb: bootstrap_nav::fallback
    menu_id: main-nav
  walker: bootstrap_nav
post-list2:
  debug_label: Post list
  debug_type: list
  type: controller
  name: tdc_get_loop
  tpl_part: basic-list
  query_args:
    post_type: produkty
    posts_per_page: "10"
    paged: "1"
  args:
    elements:
      - 
        list_type: post
        value: title
        as_url: 'true'
      - 
        list_type: meta
        value: title
        meta_name: ui_example_data
    actions:
      - 
        action_type: Edit
      - 
        action_type: Create DB Relation
        db_relation:
          db_table_name: relacje-produktow
          first_param_type: Selected item
          first_param_column_name: Parent_id
          next_params:
            - Items
            - Users
          posttype_param_column_name: Children_id
          posttype_param_type: Selected item
          posttype_param_posttype: zestawy
          user_param_role: Administrator
  tpl_start: '<table width=100% class=table>'
  tpl_end: '</table>'
excerpt-text3:
  debug_label: Excerpt
  debug_type: static
  type: tpl-part
  tpl_part: basic-excerpt-promo
  tpl_part_prop: not_implemented
footer4:
  type: tpl-part
  tpl_part: basic-footer
grid: basic-fat
ui_page_name: produkty-list
ui_slot_list_name: slot-list-for-posttype1
