---
logo0:
  type: tpl-part
  tpl_part: basic-logo-simple
nav-menu-header1:
  debug_label: Nav Menu
  debug_type: menu
  type: tpl-part
  tpl_part: basic-nav-menu-bootstrap
  menu:
    container: div
    container_class: >
      nav-menu collapse navbar-collapse
      navbar-ex1-collapse no-margin
    theme_location: main-menu-login
    menu_class: nav navbar-nav
    fallback_cb: bootstrap_nav::fallback
    menu_id: main-nav
  walker: bootstrap_nav
title-text2:
  debug_label: Title
  debug_type: static
  type: tpl-part
  tpl_part: basic-title
  tpl_part_prop: not_implemented
  element_attr:
    element_body:
      class: tiled-title tpl-part text-center
    title_wraper:
      class: big-title
  args:
    custom_title: PRODUKTY
post-meta3:
  debug_label: Post meta
  debug_type: list
  type: tpl-part
  tpl_part: basic-meta
  tpl_part_prop: not_implemented
  args:
    meta_label: Podgląd produktu
    meta_type: thumbnail
    thumbnail_size: large
  element_attr:
    content_wraper:
      style: width=100% height=auto
post-meta4:
  debug_label: Post meta
  debug_type: list
  type: tpl-part
  tpl_part: basic-meta
  tpl_part_prop: not_implemented
  args:
    meta_label: example_data
    meta_type: meta
    meta_name: ui_example_data
content-text5:
  debug_label: Content
  debug_type: static
  type: tpl-part
  tpl_part: basic-content
  tpl_part_prop: not_implemented
footer6:
  type: tpl-part
  tpl_part: basic-footer
grid: basic-article
ui_page_name: produkty-view
ui_slot_list_name: slot-list-for-posttype1
