---
logo0:
  type: tpl-part
  tpl_part: basic-logo-simple
nav-menu-header1:
  debug_label: Nav Menu
  debug_type: menu
  type: tpl-part
  tpl_part: basic-nav-menu-bootstrap
  menu:
    container: div
    container_class: >
      nav-menu collapse navbar-collapse
      navbar-ex1-collapse no-margin
    theme_location: main-menu-login
    menu_class: nav navbar-nav
    fallback_cb: bootstrap_nav::fallback
    menu_id: main-nav
  walker: bootstrap_nav
title-text2:
  debug_label: Title
  debug_type: static
  type: tpl-part
  tpl_part: tiled-title
  tpl_part_prop: not_implemented
post-list3:
  debug_label: Post list
  debug_type: list
  type: controller
  name: tdc_get_loop
  tpl_part: post-list-item
  query_args:
    post_type: produkty
    posts_per_page: "10"
    paged: "1"
  args:
    elements:
      - 
        type: post
        value: title
      - 
        type: meta
        meta_name: ui_example_data
    actions:
      - 
        action_type: Edit
      - 
        action_type: Create DB Relation
        db_relation:
          db_table_name: relacje-produktow
          first_param_type: Selected item
          first_param_column_name: Children_id
          second_param_type: Post List
          second_param_column_name: Parent_id
          second_param_posttype: zestawy
  tpl_start: '<table width=100%>'
  tpl_end: '</table>'
excerpt-text4:
  debug_label: Excerpt
  debug_type: static
  type: tpl-part
  tpl_part: basic-excerpt-promo
  tpl_part_prop: not_implemented
footer5:
  type: tpl-part
  tpl_part: basic-footer
grid: basic-fat
ui_page_name: produkty-list
ui_slot_list_name: slot-list-for-posttype1
